routes/web.php
<?php

Route::get('/', function () {
    return view('welcome');
});

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

Route::get('email-verification/error', 'EmailVerificationController@getVerificationError')->name('email-verification.error');
Route::get('email-verification/check/{token}', 'EmailVerificationController@getVerification')->name('email-verification.check');

Route::get('/home', 'HomeController@index')->name('home');

Route::group([
    'prefix' => 'admin',
    'as' => 'admin.',
    'namespace' => 'Admin\\'
], function() {
    Route::name('login')->get('login', 'Auth\LoginController@showLoginForm');
    Route::post('login','Auth\LoginController@login');

    Route::group(['middleware' => ['isVerified']], function() {//,'can:admin'
        Route::name('logout')->post('logout','Auth\LoginController@logout');
        Route::get('dashboard', function() {
            return view('admin.dashboard');
        });
        Route::name('user_settings.edit')->get('users/settings', 'Auth\UserSettingsController@edit');
        Route::name('user_settings.update')->put('users/settings', 'Auth\UserSettingsController@update');

        Route::resource('users','UsersController');
        Route::resource('categories','CategoriesController');
        Route::resource('series','SeriesController');
        Route::group(['prefix' => 'videos', 'as' => 'videos.'], function() {
            Route::name('relations.create')->get('{video}/relations','VideoRelationsController@create');
            Route::name('relations.store')->post('{video}/relations','VideoRelationsController@store');
        });
        Route::resource('videos','VideosController');

    });
});

app/Http/Controllers/Admin/SeriesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Forms\SerieForm;
use App\Http\Controllers\Controller;
use App\Models\Serie;
use App\Repositories\SerieRepository;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\Request;

class SeriesController extends Controller
{
    private $repository;

    /**
     * UsersController constructor.
     */
    public function __construct(SerieRepository $repository)
    {
        $this->repository = $repository;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $series = $this->repository->paginate();
        return view('admin.series.index', compact('series'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $form = \FormBuilder::create(SerieForm::class, [
            'url' => route('admin.series.store'),
            'method' => 'POST'
        ]);

        return view('admin.series.create', compact('form'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $form = \FormBuilder::create(SerieForm::class);

        if(!$form->isValid()){
            return redirect()
                ->back()
                ->withErrors($form->getErrors())
                ->withInput();
        }

        $data = $form->getFieldValues();
        $data['thumb'] = "thumb.jpg";

        Model::unguard();

        $this->repository->create($data);

        $request->session()->flash('message','Serie criada com sucesso.');

        return redirect()->route('admin.series.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Serie $series)
    {
        return view('admin.series.show', ['serie' => $series]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Serie $series)
    {
        $form = \FormBuilder::create(SerieForm::class, [
            'url' => route('admin.series.update', ['serie' => $series->id]),
            'method' => 'PUT',
            'model' => $series
        ]);

        return view('admin.series.edit', compact('form'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $form = \FormBuilder::create(SerieForm::class);

        if(!$form->isValid()){
            return redirect()
                ->back()
                ->withErrors($form->getErrors())
                ->withInput();
        }

        $data = array_except($form->getFieldValues(), ['password','role']);
        $this->repository->update($data, $id);

        $request->session()->flash('message','Serie alterada com sucesso.');
        return redirect()->route('admin.series.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->repository->delete($id);
        return redirect()->route('admin.series.index');
    }
}

resources/views/admin/series/create.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
    <div class="row">
        <h3>Nova Serie</h3>
        {!! form($form->add('salve','submit', [
         'attr' => ['class' => 'btn btn-primary btn-block'],
            'label' => 'Salvar'
         ])) !!}
    </div>
</div>
@endsection

resources/views/admin/series/edit.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
    <div class="row">
        <h3>Editar Serie</h3>
        {!! form($form->add('salve','submit', [
         'attr' => ['class' => 'btn btn-primary btn-block'],
            'label' => 'Salvar'
         ])) !!}
    </div>
</div>
@endsection

resources/views/admin/series/index.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
    <div class="row">
        <h3>Lista de Series</h3>
        {!! Button::primary('Nova Serie')->asLinkTo(route('admin.series.create')) !!}
    </div>
    <div class="row">
       {!! Table::withContents($series->items())->striped()
            ->callback('Ações', function($field, $serie) {
                $linkEdit = route('admin.series.edit', ['serie' => $serie->id]);
                $linkShow = route('admin.series.show', ['serie' => $serie->id]);
                return Button::link(Icon::create('pencil'))->asLinkTo($linkEdit) . "|" .
                        Button::link(Icon::create('remove'))->asLinkTo($linkShow);
            })
        !!}

        {!! $series->links() !!}
    </div>
</div>
@endsection

resources/views/admin/series/show.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
    <div class="row">
        <h3>Visualizar Usuário</h3>

        <div class="row">
            {!! Button::primary('Editar')->asLinkTo(route('admin.series.edit', ['serie' => $serie->id])) !!}
            {!! Button::danger('Excluir')->asLinkTo(route('admin.series.destroy', ['serie' => $serie->id]))
                ->addAttributes(['onclick' => "event.preventDefault(); document.getElementById(\"form-delete\").submit();"])
            !!}
            <?php $formDelete = FormBuilder::plain([
                                                    'id' => 'form-delete',
                                                    'route' => ['admin.series.destroy', 'serie' => $serie->id],
                                                    'method' => 'DELETE',
                                                    'style' => 'display:none'
                                                    ]
                                                );
                    ?>
            {!! form($formDelete) !!}

            <br />
            <br />
            <table class="table table-bordered">
                <tbody>
                <tr>
                    <td scope="row">#</td>
                    <td>{{$serie->id}}</td>
                </tr>
                <tr>
                    <td scope="row">Title</td>
                    <td>{{$serie->title}}</td>
                </tr>

                </tbody>
            </table>
        </div>
        
    </div>
</div>
@endsection