routes/web.php
<?php

Route::get('/', function () {
    return view('welcome');
});

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

Route::get('email-verification/error', 'EmailVerificationController@getVerificationError')->name('email-verification.error');
Route::get('email-verification/check/{token}', 'EmailVerificationController@getVerification')->name('email-verification.check');

Route::get('/home', 'HomeController@index')->name('home');

Route::group([
    'prefix' => 'admin',
    'as' => 'admin.',
    'namespace' => 'Admin\\'
], function() {
    Route::name('login')->get('login', 'Auth\LoginController@showLoginForm');
    Route::post('login','Auth\LoginController@login');

    Route::group(['middleware' => ['isVerified']], function() {//,'can:admin'
        Route::name('logout')->post('logout','Auth\LoginController@logout');
        Route::get('dashboard', function() {
            return view('admin.dashboard');
        });
        Route::name('user_settings.edit')->get('users/settings', 'Auth\UserSettingsController@edit');
        Route::name('user_settings.update')->put('users/settings', 'Auth\UserSettingsController@update');

        Route::resource('users','UsersController');
        Route::resource('categories','CategoriesController');
        Route::resource('series','SeriesController');
        Route::group(['prefix' => 'videos', 'as' => 'videos.'], function() {
            Route::name('relations.create')->get('{video}/relations','VideoRelationsController@create');
            Route::name('relations.store')->post('{video}/relations','VideoRelationsController@store');
        });
        Route::resource('videos','VideosController');

    });
});

app/Models/Video.php
<?php

namespace App\Models;

use Bootstrapper\Interfaces\TableInterface;
use Illuminate\Database\Eloquent\Model;
use Prettus\Repository\Contracts\Transformable;
use Prettus\Repository\Traits\TransformableTrait;

class Video extends Model implements TableInterface
{
    use TransformableTrait;

    protected $fillable = ['title','description','duration','published','serie_id'];

    /**
     * A list of headers to be used when a table is displayed
     *
     * @return array
     */
    public function getTableHeaders()
    {
       return ['#'];
    }

    /**
     * Get the value for a given header. Note that this will be the value
     * passed to any callback functions that are being used.
     *
     * @param string $header
     * @return mixed
     */
    public function getValueForHeader($header)
    {
        switch ($header) {
            case '#':
                return $this->id;
                break;
        }
    }


    public function serie()
    {
        return $this->belongsTo(Serie::class);
    }


    public function categories()
    {
        return $this->belongsToMany(Category::class);
    }
}

app/Http/Controllers/Admin/VideosController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Forms\VideoForm;
use App\Models\Video;
use App\Repositories\VideoRepository;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class VideosController extends Controller
{
    private $repository;

    /**
     * UsersController constructor.
     */
    public function __construct(VideoRepository $repository)
    {
        $this->repository = $repository;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $videos = $this->repository->paginate();
        return view('admin.videos.index', compact('videos'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $form = \FormBuilder::create(VideoForm::class, [
            'url' => route('admin.videos.store'),
            'method' => 'POST'
        ]);

        return view('admin.videos.create', compact('form'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $form = \FormBuilder::create(VideoForm::class);

        if(!$form->isValid()){
            return redirect()
                ->back()
                ->withErrors($form->getErrors())
                ->withInput();
        }

        $data = $form->getFieldValues();

        $this->repository->create($data);

        $request->session()->flash('message','Vídeo cadastrado com sucesso.');

        return redirect()->route('admin.videos.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Video $video)
    {
        return view('admin.videos.show', ['video' => $video]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Video $video)
    {
        $form = \FormBuilder::create(VideoForm::class, [
            'url' => route('admin.videos.update', ['video' => $video->id]),
            'method' => 'PUT',
            'model' => $video
        ]);

        return view('admin.videos.edit', compact('form'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $form = \FormBuilder::create(VideoForm::class);

        if(!$form->isValid()){
            return redirect()
                ->back()
                ->withErrors($form->getErrors())
                ->withInput();
        }

        $data = array_except($form->getFieldValues(), ['password','role']);
        $this->repository->update($data, $id);

        $request->session()->flash('message','Vídeo alterado com sucesso.');
        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->repository->delete($id);
        return redirect()->route('admin.series.index');
    }

    public function downloadThumbSmall(Video $video)
    {

    }
}

resources/views/admin/videos/create.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
    <div class="row">
        @component('admin.videos.tabs-component')
            <div class="col-md-12">
                <h4>Novo Vídeo</h4>
                {!! form($form->add('salve','submit', [
                 'attr' => ['class' => 'btn btn-primary btn-block'],
                    'label' => 'Salvar'
                 ])) !!}
            </div>
        @endcomponent
    </div>
</div>
@endsection

resources/views/admin/videos/edit.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
    <div class="row">
        @component('admin.videos.tabs-component', ['video' => $form->getModel()])
            <div class="col-md-12">
                <h4>Edit Vídeo</h4>
                {!! form($form->add('salve','submit', [
                 'attr' => ['class' => 'btn btn-primary btn-block'],
                    'label' => 'Salvar'
                 ])) !!}
        @endcomponent
    </div>
</div>
@endsection

resources/views/admin/videos/index.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
    <div class="row">
        <h3>Lista de Vídeos</h3>
        {!! Button::primary('Nova Serie')->asLinkTo(route('admin.videos.create')) !!}
    </div>
    <div class="row">
       {!! Table::withContents($videos->items())->striped()
           ->callback('Descrição', function($field, $video) {
                return MediaObject::withContents(
                    [
                        'image' => '//placehold.it/64x64',
                        'link' => '#',
                        'heading' => $video->title,
                        'body' => $video->description
                    ]
                );
           })
           ->callback('Ações', function($field, $video) {
                $linkEdit = route('admin.videos.edit', ['video' => $video->id]);
                $linkShow = route('admin.videos.show', ['video' => $video->id]);
                return Button::link(Icon::create('pencil'))->asLinkTo($linkEdit) . "|" .
                        Button::link(Icon::create('remove'))->asLinkTo($linkShow);
            })
        !!}

        {!! $videos->links() !!}
    </div>
</div>
@endsection

@push('styles')
<style>
    .media-body {
        width:auto;
    }
</style>
@endpush

resources/views/admin/videos/relation.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
    <div class="row">
        @component('admin.videos.tabs-component', ['video'=>$form->getModel()])
            <div class="col-md-12">
                <h4>Série e categorias</h4>
                {!! form($form->add('salve','submit', [
                 'attr' => ['class' => 'btn btn-primary btn-block'],
                    'label' => 'Salvar'
                 ])) !!}
            </div>
        @endcomponent
    </div>
</div>
@endsection

resources/views/admin/videos/show.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
    <div class="row">
        <h3>Visualizar Usuário</h3>

        <div class="row">
            {!! Button::primary('Editar')->asLinkTo(route('admin.videos.edit', ['video' => $video->id])) !!}
            {!! Button::danger('Excluir')->asLinkTo(route('admin.videos.destroy', ['video' => $video->id]))
                ->addAttributes(['onclick' => "event.preventDefault(); document.getElementById(\"form-delete\").submit();"])
            !!}
            <?php $formDelete = FormBuilder::plain([
                                                    'id' => 'form-delete',
                                                    'route' => ['admin.videos.destroy', 'video' => $video->id],
                                                    'method' => 'DELETE',
                                                    'style' => 'display:none'
                                                    ]
                                                );
                    ?>
            {!! form($formDelete) !!}

            <br />
            <br />
            <table class="table table-bordered">
                <tbody>
                <tr>
                    <td scope="row">#</td>
                    <td>{{$video->id}}</td>
                </tr>
                <tr>
                    <td scope="row">Title</td>
                    <td>{{$video->title}}</td>
                </tr>

                <tr>
                    <td scope="row">Description</td>
                    <td>{{$video->description}}</td>
                </tr>

                </tbody>
            </table>
        </div>
        
    </div>
</div>
@endsection

resources/views/admin/videos/tabs-component.blade.php
<?php

    $tabs = [
        [
            'title' => 'Informações',
            'link' => !isset($video)?route('admin.videos.create'):route('admin.videos.edit',['video'=>$video->id])
        ],
        [
            'title' => 'Séries e categorias',
            'link' => !isset($video)?'#' : route('admin.videos.relations.create',['video'=>$video->id]),
            'disabled' => !isset($video)?true : false
        ],
        [
            'title' => 'Vídeo e thumbnail',
            'link' => ''
        ]

    ]
?>

<h3>Gerenciar vídeo</h3>
<div class="text-right">
    {!! Button::link('Listar vídeos')->asLinkTo(route('admin.videos.index')) !!}
</div>

{!! Navigation::tabs($tabs) !!}

<div>
    {!! $slot !!}
</div>